# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rushi Shah
tagline:          ''
description:      ''
url:              http://rshah.io/
baseurl:          /blog/

author:
  name:           'Rushi Shah'
  url:            http://rshah.io/

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/2016rshah/blog
