# Dependencies
markdown:         redcarpet
redcarpet:   
  extensions: ["strikethrough"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rushi Shah
tagline:          '¯\_(ツ)_/¯'
description:      'Java, Python, JavaScript, Ruby, and Haskell enthusiast.'
url:              http://rshah.org/
baseurl:          /blog/

author:
  name:           'Rushi Shah'
  url:            http://rshah.org/

paginate:         20

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/2016rshah/blog
